language: generic

sudo: required

services:
  - docker

before_install:
  # - docker build -t ajaypravin/reactjsdocker -f Dockerfile.dev .
  - docker build .

script:
  - docker run -e CI=true ajaypravin/reactjsdocker npm run test
