language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ajaypravin/reactjsdocker -f dockerfile.dev .

script:
  - docker run -e CI=true ajaypravin/reactjsdocker npm run test
